defmodule BuildCalculatorWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :build_calculator

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_build_calculator_key",
    signing_salt: "AEu/Yw8w",
    same_site: "Lax"
  ]

  # Задача 4.41: потолок одного сообщения браузера по сокету LiveView — вторая
  # линия защиты за потолком вставки (`BuildCalculatorWeb.InputLimits`, там
  # же числа). Здесь он стоит на ОДИН КАДР (`max_frame_size`, умолчание
  # WebSockAdapter — 10 МБ); на сообщение из нескольких кадров — в `config.exs`
  # (`max_fragmented_message_size` у Bandit, умолчание 8 МБ). Нужны оба: Chrome
  # шлёт длинное сообщение кадрами не длиннее 131 000 байт, и предел кадра его
  # не видит вовсе (замер 4.41), а клиент, шлющий одним кадром, не видит
  # предела сообщения. Число одно — из конфига, чтобы два места не разошлись.
  @max_message_bytes Application.compile_env!(:build_calculator, :websocket_max_message_bytes)

  # Задача 4.54: адрес пира, заголовки `x-*` и User-Agent — счётчику посещений
  # (`BuildCalculatorWeb.Analytics`), только на подключённом монтировании. Сами
  # они никуда не пишутся: адрес за Caddy берётся из `X-Forwarded-For` лишь
  # у своего пира (`Analytics.Client.ip/2`), и вместе с User-Agent уходит
  # в хеш с солью дня.
  @connect_info [:peer_data, :x_headers, :user_agent, session: @session_options]

  # Задача 4.74: путь сокета и путь LongPoll внутри него — атрибутами, потому
  # что их читают двое: сам сокет и потолок тела LongPoll ниже. Путь LongPoll —
  # умолчание Phoenix (`"/longpoll"`), названное явно, чтобы потолок не стоял
  # на пути, где транспорта уже нет.
  @live_socket_path "/live"
  @longpoll_path "/longpoll"

  # Задача 4.76: `log: false` — строку о подключении пишет
  # `BuildCalculatorWeb.SocketLog`: одну и без параметров клиента (у Phoenix —
  # четыре строки с параметрами, до 8 КБ от собранного руками подключения).
  socket @live_socket_path, Phoenix.LiveView.Socket,
    websocket: [connect_info: @connect_info, max_frame_size: @max_message_bytes, log: false],
    longpoll: [connect_info: @connect_info, path: @longpoll_path, log: false]

  # Задача 4.74: тот же потолок на тело POST транспорта LongPoll. Свой плаг,
  # потому что у Phoenix опции нет (тело читается умолчанием Plug, 8 МБ, пачкой
  # до 100 сообщений), а стоит он в `call/2`, потому что сокет разбирается
  # самым первым плагом эндпоинта — `plug :socket_dispatch` из
  # `use Phoenix.Endpoint`, раньше любого `plug` этого файла. Доводы и числа —
  # `BuildCalculatorWeb.LongPollBodyLimit`.
  @longpoll_body_limit BuildCalculatorWeb.LongPollBodyLimit.init(
                         path: @live_socket_path <> @longpoll_path,
                         max_bytes: @max_message_bytes
                       )

  @doc "The ceiling on one message from the browser over the LiveView socket, in bytes."
  @spec max_message_bytes() :: pos_integer()
  def max_message_bytes, do: @max_message_bytes

  @doc false
  def longpoll_path, do: @live_socket_path <> @longpoll_path

  # Плаг-цепочка эндпоинта целиком — `super`; потолок LongPoll стоит перед ней,
  # то есть перед разбором сокета (в проде — и перед `Plug.SSL` от `force_ssl`:
  # отвергнутому телу перенаправление ни к чему). Обёртка Phoenix (`script_name`,
  # рендер ошибок) остаётся снаружи: её `__before_compile__` оборачивает этот
  # `call/2`.
  def call(conn, opts) do
    case BuildCalculatorWeb.LongPollBodyLimit.call(conn, @longpoll_body_limit) do
      %Plug.Conn{halted: true} = refused -> refused
      conn -> super(conn, opts)
    end
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :build_calculator,
    gzip: not code_reloading?,
    only: BuildCalculatorWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :build_calculator
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # Задача 4.75: строку запроса `Phoenix.Logger` («GET <путь>») выключает
  # `log: false` — путь несёт код билда (`/b/<код>`), ключ короткой ссылки,
  # id и токены. Её место занимает `RequestLog`: та же пара строк, но путь
  # назван шаблоном маршрута (`GET /b/:code`). Сами события телеметрии
  # (метрики, LiveDashboard) остаются.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false
  plug BuildCalculatorWeb.RequestLog

  # Задача 4.76: потолок тела запроса — `InputLimits.request_body/0` (доводы
  # там). Без него действовали умолчания парсеров: форма — 1 МБ, JSON
  # и multipart — 8 МБ, на любом пути и до проверки CSRF. Сверх потолка —
  # 413 (`Plug.Parsers.RequestTooLargeError`). Тела LongPoll сюда не доходят:
  # сокет разбирается раньше (`call/2` выше).
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: BuildCalculatorWeb.InputLimits.request_body(),
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BuildCalculatorWeb.Router
end
